plugins {
    id 'java-library'
    id 'maven-publish'
}

repositories {
    mavenLocal()
    mavenCentral()
    maven { url 'https://jitpack.io' }
}

dependencies {
    try {
        api project(":TranslateCore")
    } catch (UnknownProjectException ignored) {
        System.out.println("Could not find subModule of ShipsCore, using jit instead")
        api 'com.github.Minecraft-Ships:TranslateCore:master-SNAPSHOT'
    }
    implementation group: 'net.kyori', name: 'adventure-text-serializer-plain', version: '5.1.1'
    implementation group: 'net.kyori', name: 'adventure-text-serializer-legacy', version: '5.1.1'
    implementation group: 'net.kyori', name: 'adventure-text-serializer-gson', version: '5.1.1'

    compileOnly 'org.jetbrains:annotations:20.1.0'
}

group = 'org.ships'
version = '6.1.0.0'
description = 'ShipsForCore'

java {
    sourceCompatibility = JavaLanguageVersion.of(Integer.parseInt(JAVA_VERSION))
}

publishing {
    publications {
        maven(MavenPublication) {
            groupId = project.group
            artifactId = project.name
            version = project.version

            from components.java
        }
    }
}
