# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven JavaDoc

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradlew
      run: ./gradlew javadoc

    - name: Check GitHub Pages status
      uses: crazy-max/ghaction-github-status@v2
      with:
        pages_threshold: major_outage

    - name: Deploy to GitHub Pages
      uses: crazy-max/ghaction-github-pages@v2.5.0
      with:
        target_branch: gh-pages
        build_dir: build/docs/javadoc
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}